coverage:
  status:
    project:
      default:
        target: auto
        threshold: 2%
    patch: off

notify:
  after_n_builds: 2
  wait_for_ci: false

fixes:
  - "github.com/golid-ai/golid/backend/::backend/"

flags:
  backend:
    paths:
      - backend/
  frontend:
    paths:
      - frontend/src/
