# ==============================================================================
# Cloud Run Service Configuration - Frontend (REFERENCE TEMPLATE)
# This file documents the desired service configuration but is NOT used by
# deploy.sh, which deploys via gcloud run deploy with equivalent flags.
# To apply directly: gcloud run services replace infra/frontend-service.yaml
# ==============================================================================
apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: golid-web
  labels:
    app: golid
    component: frontend
  annotations:
    run.googleapis.com/description: "Golid web frontend"
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        run.googleapis.com/execution-environment: gen2
        run.googleapis.com/vpc-access-connector: projects/PROJECT_ID/locations/REGION/connectors/golid-vpc
        run.googleapis.com/vpc-access-egress: all-traffic
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "10"
        run.googleapis.com/startup-cpu-boost: "true"
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: golid-web@PROJECT_ID.iam.gserviceaccount.com
      containers:
        - image: REGION-docker.pkg.dev/PROJECT_ID/golid/web:TAG
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
          env:
            - name: NODE_ENV
              value: "production"
          startupProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 0
            periodSeconds: 2
            timeoutSeconds: 1
            failureThreshold: 30
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            periodSeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
  traffic:
    - percent: 100
      latestRevision: true
