// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	ClearPasswordResetToken(ctx context.Context, id uuid.UUID) error
	// sqlc Queries - Refresh Tokens
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (*RefreshToken, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (*User, error)
	// ============================================================================
	// EMAIL VERIFICATION (selector.verifier pattern)
	// ============================================================================
	CreateUserWithVerification(ctx context.Context, arg CreateUserWithVerificationParams) (*User, error)
	DeleteExpiredRefreshTokens(ctx context.Context) error
	// Available for account deletion feature — not yet wired to a handler.
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (*RefreshToken, error)
	GetUserByEmail(ctx context.Context, email string) (*User, error)
	// ============================================================================
	// USERS
	// ============================================================================
	GetUserByID(ctx context.Context, id uuid.UUID) (*User, error)
	// ============================================================================
	// PASSWORD RESET (selector.verifier pattern)
	// ============================================================================
	GetUserByResetSelector(ctx context.Context, passwordResetSelector pgtype.Text) (*User, error)
	GetUserByVerificationSelector(ctx context.Context, verificationSelector pgtype.Text) (*User, error)
	RevokeAllUserRefreshTokens(ctx context.Context, userID uuid.UUID) error
	RevokeRefreshToken(ctx context.Context, tokenHash string) error
	SetPasswordResetToken(ctx context.Context, arg SetPasswordResetTokenParams) error
	SetVerificationToken(ctx context.Context, arg SetVerificationTokenParams) error
	UpdatePasswordAndClearReset(ctx context.Context, arg UpdatePasswordAndClearResetParams) error
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
}

var _ Querier = (*Queries)(nil)
